---

#cluster initialization, make sure variables work for your environment.
- name: may the light, by the keeper
  shell: kubeadm init  --apiserver-advertise-address={{ ansible_ssh_host }} --apiserver-cert-extra-sans={{ ansible_ssh_host }} --pod-network-cidr=192.168.0.0/16 --node-name={{ ansible_hostname }}
  vars:
    ansible_command_timeout: 30

- name: after successfull setup, install calico CNI
  shell: curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico.yaml -O ; kubectl apply -f calico.yaml

