---
- name: edit modules and add k8s config
  ansible.builtin.copy:
    src: ../files/module-k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: modprobe config
  ansible.builtin.shell: |
    modprobe overlay 
    modprobe br_netfilter

- name: add sysctl configs for k8s
  ansible.builtin.copy:
    src: ../files/sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: apply sysctl configs
  ansible.builtin.shell: |
    sysctl --system
